<script lang="ts" setup>
import { Preview } from "./shared/index";
import * as Config from "../utils/app-config";
const htmlColorsExample = `
<AbritesIcon icon="mail" />
<AbritesIcon accent icon="mail" />
<AbritesIcon danger icon="mail" />
<AbritesIcon success icon="mail" />
<AbritesIcon warning icon="mail" />
<AbritesIcon light icon="mail" />
<AbritesIcon dark icon="mail" />
`;

const htmlFadedExample = `
<AbritesIcon faded icon="mail" />
<AbritesIcon faded accent icon="mail" />
<AbritesIcon faded danger icon="mail" />
<AbritesIcon faded success icon="mail" />
<AbritesIcon faded warning icon="mail" />
<AbritesIcon faded light icon="mail" />
<AbritesIcon faded dark icon="mail" />
`;

const htmlSizesExample = `
<AbritesIcon large icon="pan_tool" />
<AbritesIcon icon="pan_tool" />
<AbritesIcon small icon="pan_tool" />
`;

const htmlRotatesExample = `
<AbritesIcon icon="trending_flat" />
<AbritesIcon rotate-90 icon="trending_flat" />
<AbritesIcon rotate-180 icon="trending_flat" />
<AbritesIcon rotate-270 icon="trending_flat" />
`;

const htmlListExample = `
<AbritesIcon icon="3d_rotation" title="3d_rotation" />
<AbritesIcon icon="ac_unit" title="ac_unit" />
<AbritesIcon icon="access_alarm" title="access_alarm" />
<AbritesIcon icon="access_alarms" title="access_alarms" />
<AbritesIcon icon="access_time" title="access_time" />
<AbritesIcon icon="accessibility" title="accessibility" />
<AbritesIcon icon="accessible" title="accessible" />
<AbritesIcon icon="account_balance" title="account_balance" />
<AbritesIcon icon="account_balance_wallet" title="account_balance_wallet" />
<AbritesIcon icon="account_box" title="account_box" />
<AbritesIcon icon="account_circle" title="account_circle" />
<AbritesIcon icon="adb" title="adb" />
<AbritesIcon icon="add" title="add" />
<AbritesIcon icon="add_a_photo" title="add_a_photo" />
<AbritesIcon icon="add_alarm" title="add_alarm" />
<AbritesIcon icon="add_alert" title="add_alert" />
<AbritesIcon icon="add_box" title="add_box" />
<AbritesIcon icon="add_circle" title="add_circle" />
<AbritesIcon icon="add_circle_outline" title="add_circle_outline" />
<AbritesIcon icon="add_location" title="add_location" />
<AbritesIcon icon="add_shopping_cart" title="add_shopping_cart" />
<AbritesIcon icon="add_to_photos" title="add_to_photos" />
<AbritesIcon icon="add_to_queue" title="add_to_queue" />
<AbritesIcon icon="adjust" title="adjust" />
<AbritesIcon icon="airline_seat_flat" title="airline_seat_flat" />
<AbritesIcon icon="airline_seat_flat_angled" title="airline_seat_flat_angled" />
<AbritesIcon icon="airline_seat_individual_suite" title="airline_seat_individual_suite" />
<AbritesIcon icon="airline_seat_legroom_extra" title="airline_seat_legroom_extra" />
<AbritesIcon icon="airline_seat_legroom_normal" title="airline_seat_legroom_normal" />
<AbritesIcon icon="airline_seat_legroom_reduced" title="airline_seat_legroom_reduced" />
<AbritesIcon icon="airline_seat_recline_extra" title="airline_seat_recline_extra" />
<AbritesIcon icon="airline_seat_recline_normal" title="airline_seat_recline_normal" />
<AbritesIcon icon="airplanemode_active" title="airplanemode_active" />
<AbritesIcon icon="airplanemode_inactive" title="airplanemode_inactive" />
<AbritesIcon icon="airplay" title="airplay" />
<AbritesIcon icon="airport_shuttle" title="airport_shuttle" />
<AbritesIcon icon="alarm" title="alarm" />
<AbritesIcon icon="alarm_add" title="alarm_add" />
<AbritesIcon icon="alarm_off" title="alarm_off" />
<AbritesIcon icon="alarm_on" title="alarm_on" />
<AbritesIcon icon="album" title="album" />
<AbritesIcon icon="all_inclusive" title="all_inclusive" />
<AbritesIcon icon="all_out" title="all_out" />
<AbritesIcon icon="android" title="android" />
<AbritesIcon icon="announcement" title="announcement" />
<AbritesIcon icon="apps" title="apps" />
<AbritesIcon icon="archive" title="archive" />
<AbritesIcon icon="arrow_back" title="arrow_back" />
<AbritesIcon icon="arrow_downward" title="arrow_downward" />
<AbritesIcon icon="arrow_drop_down" title="arrow_drop_down" />
<AbritesIcon icon="arrow_drop_down_circle" title="arrow_drop_down_circle" />
<AbritesIcon icon="arrow_drop_up" title="arrow_drop_up" />
<AbritesIcon icon="arrow_forward" title="arrow_forward" />
<AbritesIcon icon="arrow_upward" title="arrow_upward" />
<AbritesIcon icon="art_track" title="art_track" />
<AbritesIcon icon="aspect_ratio" title="aspect_ratio" />
<AbritesIcon icon="assessment" title="assessment" />
<AbritesIcon icon="assignment" title="assignment" />
<AbritesIcon icon="assignment_ind" title="assignment_ind" />
<AbritesIcon icon="assignment_late" title="assignment_late" />
<AbritesIcon icon="assignment_return" title="assignment_return" />
<AbritesIcon icon="assignment_returned" title="assignment_returned" />
<AbritesIcon icon="assignment_turned_in" title="assignment_turned_in" />
<AbritesIcon icon="assistant" title="assistant" />
<AbritesIcon icon="assistant_photo" title="assistant_photo" />
<AbritesIcon icon="attach_file" title="attach_file" />
<AbritesIcon icon="attach_money" title="attach_money" />
<AbritesIcon icon="attachment" title="attachment" />
<AbritesIcon icon="audiotrack" title="audiotrack" />
<AbritesIcon icon="autorenew" title="autorenew" />
<AbritesIcon icon="av_timer" title="av_timer" />
<AbritesIcon icon="backspace" title="backspace" />
<AbritesIcon icon="backup" title="backup" />
<AbritesIcon icon="battery_alert" title="battery_alert" />
<AbritesIcon icon="battery_charging_full" title="battery_charging_full" />
<AbritesIcon icon="battery_full" title="battery_full" />
<AbritesIcon icon="battery_std" title="battery_std" />
<AbritesIcon icon="battery_unknown" title="battery_unknown" />
<AbritesIcon icon="beach_access" title="beach_access" />
<AbritesIcon icon="beenhere" title="beenhere" />
<AbritesIcon icon="block" title="block" />
<AbritesIcon icon="bluetooth" title="bluetooth" />
<AbritesIcon icon="bluetooth_audio" title="bluetooth_audio" />
<AbritesIcon icon="bluetooth_connected" title="bluetooth_connected" />
<AbritesIcon icon="bluetooth_disabled" title="bluetooth_disabled" />
<AbritesIcon icon="bluetooth_searching" title="bluetooth_searching" />
<AbritesIcon icon="blur_circular" title="blur_circular" />
<AbritesIcon icon="blur_linear" title="blur_linear" />
<AbritesIcon icon="blur_off" title="blur_off" />
<AbritesIcon icon="blur_on" title="blur_on" />
<AbritesIcon icon="book" title="book" />
<AbritesIcon icon="bookmark" title="bookmark" />
<AbritesIcon icon="bookmark_border" title="bookmark_border" />
<AbritesIcon icon="border_all" title="border_all" />
<AbritesIcon icon="border_bottom" title="border_bottom" />
<AbritesIcon icon="border_clear" title="border_clear" />
<AbritesIcon icon="border_color" title="border_color" />
<AbritesIcon icon="border_horizontal" title="border_horizontal" />
<AbritesIcon icon="border_inner" title="border_inner" />
<AbritesIcon icon="border_left" title="border_left" />
<AbritesIcon icon="border_outer" title="border_outer" />
<AbritesIcon icon="border_right" title="border_right" />
<AbritesIcon icon="border_style" title="border_style" />
<AbritesIcon icon="border_top" title="border_top" />
<AbritesIcon icon="border_vertical" title="border_vertical" />
<AbritesIcon icon="branding_watermark" title="branding_watermark" />
<AbritesIcon icon="brightness_1" title="brightness_1" />
<AbritesIcon icon="brightness_2" title="brightness_2" />
<AbritesIcon icon="brightness_3" title="brightness_3" />
<AbritesIcon icon="brightness_4" title="brightness_4" />
<AbritesIcon icon="brightness_5" title="brightness_5" />
<AbritesIcon icon="brightness_6" title="brightness_6" />
<AbritesIcon icon="brightness_7" title="brightness_7" />
<AbritesIcon icon="brightness_auto" title="brightness_auto" />
<AbritesIcon icon="brightness_high" title="brightness_high" />
<AbritesIcon icon="brightness_low" title="brightness_low" />
<AbritesIcon icon="brightness_medium" title="brightness_medium" />
<AbritesIcon icon="broken_image" title="broken_image" />
<AbritesIcon icon="brush" title="brush" />
<AbritesIcon icon="bubble_chart" title="bubble_chart" />
<AbritesIcon icon="bug_report" title="bug_report" />
<AbritesIcon icon="build" title="build" />
<AbritesIcon icon="burst_mode" title="burst_mode" />
<AbritesIcon icon="business" title="business" />
<AbritesIcon icon="business_center" title="business_center" />
<AbritesIcon icon="cached" title="cached" />
<AbritesIcon icon="cake" title="cake" />
<AbritesIcon icon="call" title="call" />
<AbritesIcon icon="call_end" title="call_end" />
<AbritesIcon icon="call_made" title="call_made" />
<AbritesIcon icon="call_merge" title="call_merge" />
<AbritesIcon icon="call_missed" title="call_missed" />
<AbritesIcon icon="call_missed_outgoing" title="call_missed_outgoing" />
<AbritesIcon icon="call_received" title="call_received" />
<AbritesIcon icon="call_split" title="call_split" />
<AbritesIcon icon="call_to_action" title="call_to_action" />
<AbritesIcon icon="camera" title="camera" />
<AbritesIcon icon="camera_alt" title="camera_alt" />
<AbritesIcon icon="camera_enhance" title="camera_enhance" />
<AbritesIcon icon="camera_front" title="camera_front" />
<AbritesIcon icon="camera_rear" title="camera_rear" />
<AbritesIcon icon="camera_roll" title="camera_roll" />
<AbritesIcon icon="cancel" title="cancel" />
<AbritesIcon icon="card_giftcard" title="card_giftcard" />
<AbritesIcon icon="card_membership" title="card_membership" />
<AbritesIcon icon="card_travel" title="card_travel" />
<AbritesIcon icon="casino" title="casino" />
<AbritesIcon icon="cast" title="cast" />
<AbritesIcon icon="cast_connected" title="cast_connected" />
<AbritesIcon icon="center_focus_strong" title="center_focus_strong" />
<AbritesIcon icon="center_focus_weak" title="center_focus_weak" />
<AbritesIcon icon="change_history" title="change_history" />
<AbritesIcon icon="chat" title="chat" />
<AbritesIcon icon="chat_bubble" title="chat_bubble" />
<AbritesIcon icon="chat_bubble_outline" title="chat_bubble_outline" />
<AbritesIcon icon="check" title="check" />
<AbritesIcon icon="check_box" title="check_box" />
<AbritesIcon icon="check_box_outline_blank" title="check_box_outline_blank" />
<AbritesIcon icon="check_circle" title="check_circle" />
<AbritesIcon icon="chevron_left" title="chevron_left" />
<AbritesIcon icon="chevron_right" title="chevron_right" />
<AbritesIcon icon="child_care" title="child_care" />
<AbritesIcon icon="child_friendly" title="child_friendly" />
<AbritesIcon icon="chrome_reader_mode" title="chrome_reader_mode" />
<AbritesIcon icon="class" title="class" />
<AbritesIcon icon="clear" title="clear" />
<AbritesIcon icon="clear_all" title="clear_all" />
<AbritesIcon icon="close" title="close" />
<AbritesIcon icon="closed_caption" title="closed_caption" />
<AbritesIcon icon="cloud" title="cloud" />
<AbritesIcon icon="cloud_circle" title="cloud_circle" />
<AbritesIcon icon="cloud_done" title="cloud_done" />
<AbritesIcon icon="cloud_download" title="cloud_download" />
<AbritesIcon icon="cloud_off" title="cloud_off" />
<AbritesIcon icon="cloud_queue" title="cloud_queue" />
<AbritesIcon icon="cloud_upload" title="cloud_upload" />
<AbritesIcon icon="code" title="code" />
<AbritesIcon icon="collections" title="collections" />
<AbritesIcon icon="collections_bookmark" title="collections_bookmark" />
<AbritesIcon icon="color_lens" title="color_lens" />
<AbritesIcon icon="colorize" title="colorize" />
<AbritesIcon icon="comment" title="comment" />
<AbritesIcon icon="compare" title="compare" />
<AbritesIcon icon="compare_arrows" title="compare_arrows" />
<AbritesIcon icon="computer" title="computer" />
<AbritesIcon icon="confirmation_number" title="confirmation_number" />
<AbritesIcon icon="contact_mail" title="contact_mail" />
<AbritesIcon icon="contact_phone" title="contact_phone" />
<AbritesIcon icon="contacts" title="contacts" />
<AbritesIcon icon="content_copy" title="content_copy" />
<AbritesIcon icon="content_cut" title="content_cut" />
<AbritesIcon icon="content_paste" title="content_paste" />
<AbritesIcon icon="control_point" title="control_point" />
<AbritesIcon icon="control_point_duplicate" title="control_point_duplicate" />
<AbritesIcon icon="copyright" title="copyright" />
<AbritesIcon icon="create" title="create" />
<AbritesIcon icon="create_new_folder" title="create_new_folder" />
<AbritesIcon icon="credit_card" title="credit_card" />
<AbritesIcon icon="crop" title="crop" />
<AbritesIcon icon="crop_16_9" title="crop_16_9" />
<AbritesIcon icon="crop_3_2" title="crop_3_2" />
<AbritesIcon icon="crop_5_4" title="crop_5_4" />
<AbritesIcon icon="crop_7_5" title="crop_7_5" />
<AbritesIcon icon="crop_din" title="crop_din" />
<AbritesIcon icon="crop_free" title="crop_free" />
<AbritesIcon icon="crop_landscape" title="crop_landscape" />
<AbritesIcon icon="crop_original" title="crop_original" />
<AbritesIcon icon="crop_portrait" title="crop_portrait" />
<AbritesIcon icon="crop_rotate" title="crop_rotate" />
<AbritesIcon icon="crop_square" title="crop_square" />
<AbritesIcon icon="dashboard" title="dashboard" />
<AbritesIcon icon="data_usage" title="data_usage" />
<AbritesIcon icon="date_range" title="date_range" />
<AbritesIcon icon="dehaze" title="dehaze" />
<AbritesIcon icon="delete" title="delete" />
<AbritesIcon icon="delete_forever" title="delete_forever" />
<AbritesIcon icon="delete_sweep" title="delete_sweep" />
<AbritesIcon icon="description" title="description" />
<AbritesIcon icon="desktop_mac" title="desktop_mac" />
<AbritesIcon icon="desktop_windows" title="desktop_windows" />
<AbritesIcon icon="details" title="details" />
<AbritesIcon icon="developer_board" title="developer_board" />
<AbritesIcon icon="developer_mode" title="developer_mode" />
<AbritesIcon icon="device_hub" title="device_hub" />
<AbritesIcon icon="devices" title="devices" />
<AbritesIcon icon="devices_other" title="devices_other" />
<AbritesIcon icon="dialer_sip" title="dialer_sip" />
<AbritesIcon icon="dialpad" title="dialpad" />
<AbritesIcon icon="directions" title="directions" />
<AbritesIcon icon="directions_bike" title="directions_bike" />
<AbritesIcon icon="directions_boat" title="directions_boat" />
<AbritesIcon icon="directions_bus" title="directions_bus" />
<AbritesIcon icon="directions_car" title="directions_car" />
<AbritesIcon icon="directions_railway" title="directions_railway" />
<AbritesIcon icon="directions_run" title="directions_run" />
<AbritesIcon icon="directions_subway" title="directions_subway" />
<AbritesIcon icon="directions_transit" title="directions_transit" />
<AbritesIcon icon="directions_walk" title="directions_walk" />
<AbritesIcon icon="disc_full" title="disc_full" />
<AbritesIcon icon="dns" title="dns" />
<AbritesIcon icon="do_not_disturb" title="do_not_disturb" />
<AbritesIcon icon="do_not_disturb_alt" title="do_not_disturb_alt" />
<AbritesIcon icon="do_not_disturb_off" title="do_not_disturb_off" />
<AbritesIcon icon="do_not_disturb_on" title="do_not_disturb_on" />
<AbritesIcon icon="dock" title="dock" />
<AbritesIcon icon="domain" title="domain" />
<AbritesIcon icon="done" title="done" />
<AbritesIcon icon="done_all" title="done_all" />
<AbritesIcon icon="donut_large" title="donut_large" />
<AbritesIcon icon="donut_small" title="donut_small" />
<AbritesIcon icon="drafts" title="drafts" />
<AbritesIcon icon="drag_handle" title="drag_handle" />
<AbritesIcon icon="drive_eta" title="drive_eta" />
<AbritesIcon icon="dvr" title="dvr" />
<AbritesIcon icon="edit" title="edit" />
<AbritesIcon icon="edit_location" title="edit_location" />
<AbritesIcon icon="eject" title="eject" />
<AbritesIcon icon="email" title="email" />
<AbritesIcon icon="enhanced_encryption" title="enhanced_encryption" />
<AbritesIcon icon="equalizer" title="equalizer" />
<AbritesIcon icon="error" title="error" />
<AbritesIcon icon="error_outline" title="error_outline" />
<AbritesIcon icon="euro_symbol" title="euro_symbol" />
<AbritesIcon icon="ev_station" title="ev_station" />
<AbritesIcon icon="event" title="event" />
<AbritesIcon icon="event_available" title="event_available" />
<AbritesIcon icon="event_busy" title="event_busy" />
<AbritesIcon icon="event_note" title="event_note" />
<AbritesIcon icon="event_seat" title="event_seat" />
<AbritesIcon icon="exit_to_app" title="exit_to_app" />
<AbritesIcon icon="expand_less" title="expand_less" />
<AbritesIcon icon="expand_more" title="expand_more" />
<AbritesIcon icon="explicit" title="explicit" />
<AbritesIcon icon="explore" title="explore" />
<AbritesIcon icon="exposure" title="exposure" />
<AbritesIcon icon="exposure_neg_1" title="exposure_neg_1" />
<AbritesIcon icon="exposure_neg_2" title="exposure_neg_2" />
<AbritesIcon icon="exposure_plus_1" title="exposure_plus_1" />
<AbritesIcon icon="exposure_plus_2" title="exposure_plus_2" />
<AbritesIcon icon="exposure_zero" title="exposure_zero" />
<AbritesIcon icon="extension" title="extension" />
<AbritesIcon icon="face" title="face" />
<AbritesIcon icon="fast_forward" title="fast_forward" />
<AbritesIcon icon="fast_rewind" title="fast_rewind" />
<AbritesIcon icon="favorite" title="favorite" />
<AbritesIcon icon="favorite_border" title="favorite_border" />
<AbritesIcon icon="featured_play_list" title="featured_play_list" />
<AbritesIcon icon="featured_video" title="featured_video" />
<AbritesIcon icon="feedback" title="feedback" />
<AbritesIcon icon="fiber_dvr" title="fiber_dvr" />
<AbritesIcon icon="fiber_manual_record" title="fiber_manual_record" />
<AbritesIcon icon="fiber_new" title="fiber_new" />
<AbritesIcon icon="fiber_pin" title="fiber_pin" />
<AbritesIcon icon="fiber_smart_record" title="fiber_smart_record" />
<AbritesIcon icon="file_download" title="file_download" />
<AbritesIcon icon="file_upload" title="file_upload" />
<AbritesIcon icon="filter" title="filter" />
<AbritesIcon icon="filter_1" title="filter_1" />
<AbritesIcon icon="filter_2" title="filter_2" />
<AbritesIcon icon="filter_3" title="filter_3" />
<AbritesIcon icon="filter_4" title="filter_4" />
<AbritesIcon icon="filter_5" title="filter_5" />
<AbritesIcon icon="filter_6" title="filter_6" />
<AbritesIcon icon="filter_7" title="filter_7" />
<AbritesIcon icon="filter_8" title="filter_8" />
<AbritesIcon icon="filter_9" title="filter_9" />
<AbritesIcon icon="filter_9_plus" title="filter_9_plus" />
<AbritesIcon icon="filter_b_and_w" title="filter_b_and_w" />
<AbritesIcon icon="filter_center_focus" title="filter_center_focus" />
<AbritesIcon icon="filter_drama" title="filter_drama" />
<AbritesIcon icon="filter_frames" title="filter_frames" />
<AbritesIcon icon="filter_hdr" title="filter_hdr" />
<AbritesIcon icon="filter_list" title="filter_list" />
<AbritesIcon icon="filter_none" title="filter_none" />
<AbritesIcon icon="filter_tilt_shift" title="filter_tilt_shift" />
<AbritesIcon icon="filter_vintage" title="filter_vintage" />
<AbritesIcon icon="find_in_page" title="find_in_page" />
<AbritesIcon icon="find_replace" title="find_replace" />
<AbritesIcon icon="fingerprint" title="fingerprint" />
<AbritesIcon icon="first_page" title="first_page" />
<AbritesIcon icon="fitness_center" title="fitness_center" />
<AbritesIcon icon="flag" title="flag" />
<AbritesIcon icon="flare" title="flare" />
<AbritesIcon icon="flash_auto" title="flash_auto" />
<AbritesIcon icon="flash_off" title="flash_off" />
<AbritesIcon icon="flash_on" title="flash_on" />
<AbritesIcon icon="flight" title="flight" />
<AbritesIcon icon="flight_land" title="flight_land" />
<AbritesIcon icon="flight_takeoff" title="flight_takeoff" />
<AbritesIcon icon="flip" title="flip" />
<AbritesIcon icon="flip_to_back" title="flip_to_back" />
<AbritesIcon icon="flip_to_front" title="flip_to_front" />
<AbritesIcon icon="folder" title="folder" />
<AbritesIcon icon="folder_open" title="folder_open" />
<AbritesIcon icon="folder_shared" title="folder_shared" />
<AbritesIcon icon="folder_special" title="folder_special" />
<AbritesIcon icon="font_download" title="font_download" />
<AbritesIcon icon="format_align_center" title="format_align_center" />
<AbritesIcon icon="format_align_justify" title="format_align_justify" />
<AbritesIcon icon="format_align_left" title="format_align_left" />
<AbritesIcon icon="format_align_right" title="format_align_right" />
<AbritesIcon icon="format_bold" title="format_bold" />
<AbritesIcon icon="format_clear" title="format_clear" />
<AbritesIcon icon="format_color_fill" title="format_color_fill" />
<AbritesIcon icon="format_color_reset" title="format_color_reset" />
<AbritesIcon icon="format_color_text" title="format_color_text" />
<AbritesIcon icon="format_indent_decrease" title="format_indent_decrease" />
<AbritesIcon icon="format_indent_increase" title="format_indent_increase" />
<AbritesIcon icon="format_italic" title="format_italic" />
<AbritesIcon icon="format_line_spacing" title="format_line_spacing" />
<AbritesIcon icon="format_list_bulleted" title="format_list_bulleted" />
<AbritesIcon icon="format_list_numbered" title="format_list_numbered" />
<AbritesIcon icon="format_paint" title="format_paint" />
<AbritesIcon icon="format_quote" title="format_quote" />
<AbritesIcon icon="format_shapes" title="format_shapes" />
<AbritesIcon icon="format_size" title="format_size" />
<AbritesIcon icon="format_strikethrough" title="format_strikethrough" />
<AbritesIcon icon="format_textdirection_l_to_r" title="format_textdirection_l_to_r" />
<AbritesIcon icon="format_textdirection_r_to_l" title="format_textdirection_r_to_l" />
<AbritesIcon icon="format_underlined" title="format_underlined" />
<AbritesIcon icon="forum" title="forum" />
<AbritesIcon icon="forward" title="forward" />
<AbritesIcon icon="forward_10" title="forward_10" />
<AbritesIcon icon="forward_30" title="forward_30" />
<AbritesIcon icon="forward_5" title="forward_5" />
<AbritesIcon icon="free_breakfast" title="free_breakfast" />
<AbritesIcon icon="fullscreen" title="fullscreen" />
<AbritesIcon icon="fullscreen_exit" title="fullscreen_exit" />
<AbritesIcon icon="functions" title="functions" />
<AbritesIcon icon="g_translate" title="g_translate" />
<AbritesIcon icon="gamepad" title="gamepad" />
<AbritesIcon icon="games" title="games" />
<AbritesIcon icon="gavel" title="gavel" />
<AbritesIcon icon="gesture" title="gesture" />
<AbritesIcon icon="get_app" title="get_app" />
<AbritesIcon icon="gif" title="gif" />
<AbritesIcon icon="golf_course" title="golf_course" />
<AbritesIcon icon="gps_fixed" title="gps_fixed" />
<AbritesIcon icon="gps_not_fixed" title="gps_not_fixed" />
<AbritesIcon icon="gps_off" title="gps_off" />
<AbritesIcon icon="grade" title="grade" />
<AbritesIcon icon="gradient" title="gradient" />
<AbritesIcon icon="grain" title="grain" />
<AbritesIcon icon="graphic_eq" title="graphic_eq" />
<AbritesIcon icon="grid_off" title="grid_off" />
<AbritesIcon icon="grid_on" title="grid_on" />
<AbritesIcon icon="group" title="group" />
<AbritesIcon icon="group_add" title="group_add" />
<AbritesIcon icon="group_work" title="group_work" />
<AbritesIcon icon="hd" title="hd" />
<AbritesIcon icon="hdr_off" title="hdr_off" />
<AbritesIcon icon="hdr_on" title="hdr_on" />
<AbritesIcon icon="hdr_strong" title="hdr_strong" />
<AbritesIcon icon="hdr_weak" title="hdr_weak" />
<AbritesIcon icon="headset" title="headset" />
<AbritesIcon icon="headset_mic" title="headset_mic" />
<AbritesIcon icon="healing" title="healing" />
<AbritesIcon icon="hearing" title="hearing" />
<AbritesIcon icon="help" title="help" />
<AbritesIcon icon="help_outline" title="help_outline" />
<AbritesIcon icon="high_quality" title="high_quality" />
<AbritesIcon icon="highlight" title="highlight" />
<AbritesIcon icon="highlight_off" title="highlight_off" />
<AbritesIcon icon="history" title="history" />
<AbritesIcon icon="home" title="home" />
<AbritesIcon icon="hot_tub" title="hot_tub" />
<AbritesIcon icon="hotel" title="hotel" />
<AbritesIcon icon="hourglass_empty" title="hourglass_empty" />
<AbritesIcon icon="hourglass_full" title="hourglass_full" />
<AbritesIcon icon="http" title="http" />
<AbritesIcon icon="https" title="https" />
<AbritesIcon icon="image" title="image" />
<AbritesIcon icon="image_aspect_ratio" title="image_aspect_ratio" />
<AbritesIcon icon="import_contacts" title="import_contacts" />
<AbritesIcon icon="import_export" title="import_export" />
<AbritesIcon icon="important_devices" title="important_devices" />
<AbritesIcon icon="inbox" title="inbox" />
<AbritesIcon icon="indeterminate_check_box" title="indeterminate_check_box" />
<AbritesIcon icon="info" title="info" />
<AbritesIcon icon="info_outline" title="info_outline" />
<AbritesIcon icon="input" title="input" />
<AbritesIcon icon="insert_chart" title="insert_chart" />
<AbritesIcon icon="insert_comment" title="insert_comment" />
<AbritesIcon icon="insert_drive_file" title="insert_drive_file" />
<AbritesIcon icon="insert_emoticon" title="insert_emoticon" />
<AbritesIcon icon="insert_invitation" title="insert_invitation" />
<AbritesIcon icon="insert_link" title="insert_link" />
<AbritesIcon icon="insert_photo" title="insert_photo" />
<AbritesIcon icon="invert_colors" title="invert_colors" />
<AbritesIcon icon="invert_colors_off" title="invert_colors_off" />
<AbritesIcon icon="iso" title="iso" />
<AbritesIcon icon="keyboard" title="keyboard" />
<AbritesIcon icon="keyboard_arrow_down" title="keyboard_arrow_down" />
<AbritesIcon icon="keyboard_arrow_left" title="keyboard_arrow_left" />
<AbritesIcon icon="keyboard_arrow_right" title="keyboard_arrow_right" />
<AbritesIcon icon="keyboard_arrow_up" title="keyboard_arrow_up" />
<AbritesIcon icon="keyboard_backspace" title="keyboard_backspace" />
<AbritesIcon icon="keyboard_capslock" title="keyboard_capslock" />
<AbritesIcon icon="keyboard_hide" title="keyboard_hide" />
<AbritesIcon icon="keyboard_return" title="keyboard_return" />
<AbritesIcon icon="keyboard_tab" title="keyboard_tab" />
<AbritesIcon icon="keyboard_voice" title="keyboard_voice" />
<AbritesIcon icon="kitchen" title="kitchen" />
<AbritesIcon icon="label" title="label" />
<AbritesIcon icon="label_outline" title="label_outline" />
<AbritesIcon icon="landscape" title="landscape" />
<AbritesIcon icon="language" title="language" />
<AbritesIcon icon="laptop" title="laptop" />
<AbritesIcon icon="laptop_chromebook" title="laptop_chromebook" />
<AbritesIcon icon="laptop_mac" title="laptop_mac" />
<AbritesIcon icon="laptop_windows" title="laptop_windows" />
<AbritesIcon icon="last_page" title="last_page" />
<AbritesIcon icon="launch" title="launch" />
<AbritesIcon icon="layers" title="layers" />
<AbritesIcon icon="layers_clear" title="layers_clear" />
<AbritesIcon icon="leak_add" title="leak_add" />
<AbritesIcon icon="leak_remove" title="leak_remove" />
<AbritesIcon icon="lens" title="lens" />
<AbritesIcon icon="library_add" title="library_add" />
<AbritesIcon icon="library_books" title="library_books" />
<AbritesIcon icon="library_music" title="library_music" />
<AbritesIcon icon="lightbulb_outline" title="lightbulb_outline" />
<AbritesIcon icon="line_style" title="line_style" />
<AbritesIcon icon="line_weight" title="line_weight" />
<AbritesIcon icon="linear_scale" title="linear_scale" />
<AbritesIcon icon="link" title="link" />
<AbritesIcon icon="linked_camera" title="linked_camera" />
<AbritesIcon icon="list" title="list" />
<AbritesIcon icon="live_help" title="live_help" />
<AbritesIcon icon="live_tv" title="live_tv" />
<AbritesIcon icon="local_activity" title="local_activity" />
<AbritesIcon icon="local_airport" title="local_airport" />
<AbritesIcon icon="local_atm" title="local_atm" />
<AbritesIcon icon="local_bar" title="local_bar" />
<AbritesIcon icon="local_cafe" title="local_cafe" />
<AbritesIcon icon="local_car_wash" title="local_car_wash" />
<AbritesIcon icon="local_convenience_store" title="local_convenience_store" />
<AbritesIcon icon="local_dining" title="local_dining" />
<AbritesIcon icon="local_drink" title="local_drink" />
<AbritesIcon icon="local_florist" title="local_florist" />
<AbritesIcon icon="local_gas_station" title="local_gas_station" />
<AbritesIcon icon="local_grocery_store" title="local_grocery_store" />
<AbritesIcon icon="local_hospital" title="local_hospital" />
<AbritesIcon icon="local_hotel" title="local_hotel" />
<AbritesIcon icon="local_laundry_service" title="local_laundry_service" />
<AbritesIcon icon="local_library" title="local_library" />
<AbritesIcon icon="local_mall" title="local_mall" />
<AbritesIcon icon="local_movies" title="local_movies" />
<AbritesIcon icon="local_offer" title="local_offer" />
<AbritesIcon icon="local_parking" title="local_parking" />
<AbritesIcon icon="local_pharmacy" title="local_pharmacy" />
<AbritesIcon icon="local_phone" title="local_phone" />
<AbritesIcon icon="local_pizza" title="local_pizza" />
<AbritesIcon icon="local_play" title="local_play" />
<AbritesIcon icon="local_post_office" title="local_post_office" />
<AbritesIcon icon="local_printshop" title="local_printshop" />
<AbritesIcon icon="local_see" title="local_see" />
<AbritesIcon icon="local_shipping" title="local_shipping" />
<AbritesIcon icon="local_taxi" title="local_taxi" />
<AbritesIcon icon="location_city" title="location_city" />
<AbritesIcon icon="location_disabled" title="location_disabled" />
<AbritesIcon icon="location_off" title="location_off" />
<AbritesIcon icon="location_on" title="location_on" />
<AbritesIcon icon="location_searching" title="location_searching" />
<AbritesIcon icon="lock" title="lock" />
<AbritesIcon icon="lock_open" title="lock_open" />
<AbritesIcon icon="lock_outline" title="lock_outline" />
<AbritesIcon icon="looks" title="looks" />
<AbritesIcon icon="looks_3" title="looks_3" />
<AbritesIcon icon="looks_4" title="looks_4" />
<AbritesIcon icon="looks_5" title="looks_5" />
<AbritesIcon icon="looks_6" title="looks_6" />
<AbritesIcon icon="looks_one" title="looks_one" />
<AbritesIcon icon="looks_two" title="looks_two" />
<AbritesIcon icon="loop" title="loop" />
<AbritesIcon icon="loupe" title="loupe" />
<AbritesIcon icon="low_priority" title="low_priority" />
<AbritesIcon icon="loyalty" title="loyalty" />
<AbritesIcon icon="mail" title="mail" />
<AbritesIcon icon="mail_outline" title="mail_outline" />
<AbritesIcon icon="map" title="map" />
<AbritesIcon icon="markunread" title="markunread" />
<AbritesIcon icon="markunread_mailbox" title="markunread_mailbox" />
<AbritesIcon icon="memory" title="memory" />
<AbritesIcon icon="menu" title="menu" />
<AbritesIcon icon="merge_type" title="merge_type" />
<AbritesIcon icon="message" title="message" />
<AbritesIcon icon="mic" title="mic" />
<AbritesIcon icon="mic_none" title="mic_none" />
<AbritesIcon icon="mic_off" title="mic_off" />
<AbritesIcon icon="mms" title="mms" />
<AbritesIcon icon="mode_comment" title="mode_comment" />
<AbritesIcon icon="mode_edit" title="mode_edit" />
<AbritesIcon icon="monetization_on" title="monetization_on" />
<AbritesIcon icon="money_off" title="money_off" />
<AbritesIcon icon="monochrome_photos" title="monochrome_photos" />
<AbritesIcon icon="mood" title="mood" />
<AbritesIcon icon="mood_bad" title="mood_bad" />
<AbritesIcon icon="more" title="more" />
<AbritesIcon icon="more_horiz" title="more_horiz" />
<AbritesIcon icon="more_vert" title="more_vert" />
<AbritesIcon icon="motorcycle" title="motorcycle" />
<AbritesIcon icon="mouse" title="mouse" />
<AbritesIcon icon="move_to_inbox" title="move_to_inbox" />
<AbritesIcon icon="movie" title="movie" />
<AbritesIcon icon="movie_creation" title="movie_creation" />
<AbritesIcon icon="movie_filter" title="movie_filter" />
<AbritesIcon icon="multiline_chart" title="multiline_chart" />
<AbritesIcon icon="music_note" title="music_note" />
<AbritesIcon icon="music_video" title="music_video" />
<AbritesIcon icon="my_location" title="my_location" />
<AbritesIcon icon="nature" title="nature" />
<AbritesIcon icon="nature_people" title="nature_people" />
<AbritesIcon icon="navigate_before" title="navigate_before" />
<AbritesIcon icon="navigate_next" title="navigate_next" />
<AbritesIcon icon="navigation" title="navigation" />
<AbritesIcon icon="near_me" title="near_me" />
<AbritesIcon icon="network_cell" title="network_cell" />
<AbritesIcon icon="network_check" title="network_check" />
<AbritesIcon icon="network_locked" title="network_locked" />
<AbritesIcon icon="network_wifi" title="network_wifi" />
<AbritesIcon icon="new_releases" title="new_releases" />
<AbritesIcon icon="next_week" title="next_week" />
<AbritesIcon icon="nfc" title="nfc" />
<AbritesIcon icon="no_encryption" title="no_encryption" />
<AbritesIcon icon="no_sim" title="no_sim" />
<AbritesIcon icon="not_interested" title="not_interested" />
<AbritesIcon icon="note" title="note" />
<AbritesIcon icon="note_add" title="note_add" />
<AbritesIcon icon="notifications" title="notifications" />
<AbritesIcon icon="notifications_active" title="notifications_active" />
<AbritesIcon icon="notifications_none" title="notifications_none" />
<AbritesIcon icon="notifications_off" title="notifications_off" />
<AbritesIcon icon="notifications_paused" title="notifications_paused" />
<AbritesIcon icon="offline_pin" title="offline_pin" />
<AbritesIcon icon="ondemand_video" title="ondemand_video" />
<AbritesIcon icon="opacity" title="opacity" />
<AbritesIcon icon="open_in_browser" title="open_in_browser" />
<AbritesIcon icon="open_in_new" title="open_in_new" />
<AbritesIcon icon="open_with" title="open_with" />
<AbritesIcon icon="pages" title="pages" />
<AbritesIcon icon="pageview" title="pageview" />
<AbritesIcon icon="palette" title="palette" />
<AbritesIcon icon="pan_tool" title="pan_tool" />
<AbritesIcon icon="panorama" title="panorama" />
<AbritesIcon icon="panorama_fish_eye" title="panorama_fish_eye" />
<AbritesIcon icon="panorama_horizontal" title="panorama_horizontal" />
<AbritesIcon icon="panorama_vertical" title="panorama_vertical" />
<AbritesIcon icon="panorama_wide_angle" title="panorama_wide_angle" />
<AbritesIcon icon="party_mode" title="party_mode" />
<AbritesIcon icon="pause" title="pause" />
<AbritesIcon icon="pause_circle_filled" title="pause_circle_filled" />
<AbritesIcon icon="pause_circle_outline" title="pause_circle_outline" />
<AbritesIcon icon="payment" title="payment" />
<AbritesIcon icon="people" title="people" />
<AbritesIcon icon="people_outline" title="people_outline" />
<AbritesIcon icon="perm_camera_mic" title="perm_camera_mic" />
<AbritesIcon icon="perm_contact_calendar" title="perm_contact_calendar" />
<AbritesIcon icon="perm_data_setting" title="perm_data_setting" />
<AbritesIcon icon="perm_device_information" title="perm_device_information" />
<AbritesIcon icon="perm_identity" title="perm_identity" />
<AbritesIcon icon="perm_media" title="perm_media" />
<AbritesIcon icon="perm_phone_msg" title="perm_phone_msg" />
<AbritesIcon icon="perm_scan_wifi" title="perm_scan_wifi" />
<AbritesIcon icon="person" title="person" />
<AbritesIcon icon="person_add" title="person_add" />
<AbritesIcon icon="person_outline" title="person_outline" />
<AbritesIcon icon="person_pin" title="person_pin" />
<AbritesIcon icon="person_pin_circle" title="person_pin_circle" />
<AbritesIcon icon="personal_video" title="personal_video" />
<AbritesIcon icon="pets" title="pets" />
<AbritesIcon icon="phone" title="phone" />
<AbritesIcon icon="phone_android" title="phone_android" />
<AbritesIcon icon="phone_bluetooth_speaker" title="phone_bluetooth_speaker" />
<AbritesIcon icon="phone_forwarded" title="phone_forwarded" />
<AbritesIcon icon="phone_in_talk" title="phone_in_talk" />
<AbritesIcon icon="phone_iphone" title="phone_iphone" />
<AbritesIcon icon="phone_locked" title="phone_locked" />
<AbritesIcon icon="phone_missed" title="phone_missed" />
<AbritesIcon icon="phone_paused" title="phone_paused" />
<AbritesIcon icon="phonelink" title="phonelink" />
<AbritesIcon icon="phonelink_erase" title="phonelink_erase" />
<AbritesIcon icon="phonelink_lock" title="phonelink_lock" />
<AbritesIcon icon="phonelink_off" title="phonelink_off" />
<AbritesIcon icon="phonelink_ring" title="phonelink_ring" />
<AbritesIcon icon="phonelink_setup" title="phonelink_setup" />
<AbritesIcon icon="photo" title="photo" />
<AbritesIcon icon="photo_album" title="photo_album" />
<AbritesIcon icon="photo_camera" title="photo_camera" />
<AbritesIcon icon="photo_filter" title="photo_filter" />
<AbritesIcon icon="photo_library" title="photo_library" />
<AbritesIcon icon="photo_size_select_actual" title="photo_size_select_actual" />
<AbritesIcon icon="photo_size_select_large" title="photo_size_select_large" />
<AbritesIcon icon="photo_size_select_small" title="photo_size_select_small" />
<AbritesIcon icon="picture_as_pdf" title="picture_as_pdf" />
<AbritesIcon icon="picture_in_picture" title="picture_in_picture" />
<AbritesIcon icon="picture_in_picture_alt" title="picture_in_picture_alt" />
<AbritesIcon icon="pie_chart" title="pie_chart" />
<AbritesIcon icon="pie_chart_outlined" title="pie_chart_outlined" />
<AbritesIcon icon="pin_drop" title="pin_drop" />
<AbritesIcon icon="place" title="place" />
<AbritesIcon icon="play_arrow" title="play_arrow" />
<AbritesIcon icon="play_circle_filled" title="play_circle_filled" />
<AbritesIcon icon="play_circle_outline" title="play_circle_outline" />
<AbritesIcon icon="play_for_work" title="play_for_work" />
<AbritesIcon icon="playlist_add" title="playlist_add" />
<AbritesIcon icon="playlist_add_check" title="playlist_add_check" />
<AbritesIcon icon="playlist_play" title="playlist_play" />
<AbritesIcon icon="plus_one" title="plus_one" />
<AbritesIcon icon="poll" title="poll" />
<AbritesIcon icon="polymer" title="polymer" />
<AbritesIcon icon="pool" title="pool" />
<AbritesIcon icon="portable_wifi_off" title="portable_wifi_off" />
<AbritesIcon icon="portrait" title="portrait" />
<AbritesIcon icon="power" title="power" />
<AbritesIcon icon="power_input" title="power_input" />
<AbritesIcon icon="power_settings_new" title="power_settings_new" />
<AbritesIcon icon="pregnant_woman" title="pregnant_woman" />
<AbritesIcon icon="present_to_all" title="present_to_all" />
<AbritesIcon icon="print" title="print" />
<AbritesIcon icon="priority_high" title="priority_high" />
<AbritesIcon icon="public" title="public" />
<AbritesIcon icon="publish" title="publish" />
<AbritesIcon icon="query_builder" title="query_builder" />
<AbritesIcon icon="question_answer" title="question_answer" />
<AbritesIcon icon="queue" title="queue" />
<AbritesIcon icon="queue_music" title="queue_music" />
<AbritesIcon icon="queue_play_next" title="queue_play_next" />
<AbritesIcon icon="radio" title="radio" />
<AbritesIcon icon="radio_button_checked" title="radio_button_checked" />
<AbritesIcon icon="radio_button_unchecked" title="radio_button_unchecked" />
<AbritesIcon icon="rate_review" title="rate_review" />
<AbritesIcon icon="receipt" title="receipt" />
<AbritesIcon icon="recent_actors" title="recent_actors" />
<AbritesIcon icon="record_voice_over" title="record_voice_over" />
<AbritesIcon icon="redeem" title="redeem" />
<AbritesIcon icon="redo" title="redo" />
<AbritesIcon icon="refresh" title="refresh" />
<AbritesIcon icon="remove" title="remove" />
<AbritesIcon icon="remove_circle" title="remove_circle" />
<AbritesIcon icon="remove_circle_outline" title="remove_circle_outline" />
<AbritesIcon icon="remove_from_queue" title="remove_from_queue" />
<AbritesIcon icon="remove_red_eye" title="remove_red_eye" />
<AbritesIcon icon="remove_shopping_cart" title="remove_shopping_cart" />
<AbritesIcon icon="reorder" title="reorder" />
<AbritesIcon icon="repeat" title="repeat" />
<AbritesIcon icon="repeat_one" title="repeat_one" />
<AbritesIcon icon="replay" title="replay" />
<AbritesIcon icon="replay_10" title="replay_10" />
<AbritesIcon icon="replay_30" title="replay_30" />
<AbritesIcon icon="replay_5" title="replay_5" />
<AbritesIcon icon="reply" title="reply" />
<AbritesIcon icon="reply_all" title="reply_all" />
<AbritesIcon icon="report" title="report" />
<AbritesIcon icon="report_problem" title="report_problem" />
<AbritesIcon icon="restaurant" title="restaurant" />
<AbritesIcon icon="restaurant_menu" title="restaurant_menu" />
<AbritesIcon icon="restore" title="restore" />
<AbritesIcon icon="restore_page" title="restore_page" />
<AbritesIcon icon="ring_volume" title="ring_volume" />
<AbritesIcon icon="room" title="room" />
<AbritesIcon icon="room_service" title="room_service" />
<AbritesIcon icon="rotate_90_degrees_ccw" title="rotate_90_degrees_ccw" />
<AbritesIcon icon="rotate_left" title="rotate_left" />
<AbritesIcon icon="rotate_right" title="rotate_right" />
<AbritesIcon icon="rounded_corner" title="rounded_corner" />
<AbritesIcon icon="router" title="router" />
<AbritesIcon icon="rowing" title="rowing" />
<AbritesIcon icon="rss_feed" title="rss_feed" />
<AbritesIcon icon="rv_hookup" title="rv_hookup" />
<AbritesIcon icon="satellite" title="satellite" />
<AbritesIcon icon="save" title="save" />
<AbritesIcon icon="scanner" title="scanner" />
<AbritesIcon icon="schedule" title="schedule" />
<AbritesIcon icon="school" title="school" />
<AbritesIcon icon="screen_lock_landscape" title="screen_lock_landscape" />
<AbritesIcon icon="screen_lock_portrait" title="screen_lock_portrait" />
<AbritesIcon icon="screen_lock_rotation" title="screen_lock_rotation" />
<AbritesIcon icon="screen_rotation" title="screen_rotation" />
<AbritesIcon icon="screen_share" title="screen_share" />
<AbritesIcon icon="sd_card" title="sd_card" />
<AbritesIcon icon="sd_storage" title="sd_storage" />
<AbritesIcon icon="search" title="search" />
<AbritesIcon icon="security" title="security" />
<AbritesIcon icon="select_all" title="select_all" />
<AbritesIcon icon="send" title="send" />
<AbritesIcon icon="sentiment_dissatisfied" title="sentiment_dissatisfied" />
<AbritesIcon icon="sentiment_neutral" title="sentiment_neutral" />
<AbritesIcon icon="sentiment_satisfied" title="sentiment_satisfied" />
<AbritesIcon icon="sentiment_very_dissatisfied" title="sentiment_very_dissatisfied" />
<AbritesIcon icon="sentiment_very_satisfied" title="sentiment_very_satisfied" />
<AbritesIcon icon="settings" title="settings" />
<AbritesIcon icon="settings_applications" title="settings_applications" />
<AbritesIcon icon="settings_backup_restore" title="settings_backup_restore" />
<AbritesIcon icon="settings_bluetooth" title="settings_bluetooth" />
<AbritesIcon icon="settings_brightness" title="settings_brightness" />
<AbritesIcon icon="settings_cell" title="settings_cell" />
<AbritesIcon icon="settings_ethernet" title="settings_ethernet" />
<AbritesIcon icon="settings_input_antenna" title="settings_input_antenna" />
<AbritesIcon icon="settings_input_component" title="settings_input_component" />
<AbritesIcon icon="settings_input_composite" title="settings_input_composite" />
<AbritesIcon icon="settings_input_hdmi" title="settings_input_hdmi" />
<AbritesIcon icon="settings_input_svideo" title="settings_input_svideo" />
<AbritesIcon icon="settings_overscan" title="settings_overscan" />
<AbritesIcon icon="settings_phone" title="settings_phone" />
<AbritesIcon icon="settings_power" title="settings_power" />
<AbritesIcon icon="settings_remote" title="settings_remote" />
<AbritesIcon icon="settings_system_daydream" title="settings_system_daydream" />
<AbritesIcon icon="settings_voice" title="settings_voice" />
<AbritesIcon icon="share" title="share" />
<AbritesIcon icon="shop" title="shop" />
<AbritesIcon icon="shop_two" title="shop_two" />
<AbritesIcon icon="shopping_basket" title="shopping_basket" />
<AbritesIcon icon="shopping_cart" title="shopping_cart" />
<AbritesIcon icon="short_text" title="short_text" />
<AbritesIcon icon="show_chart" title="show_chart" />
<AbritesIcon icon="shuffle" title="shuffle" />
<AbritesIcon icon="signal_cellular_4_bar" title="signal_cellular_4_bar" />
<AbritesIcon icon="signal_cellular_connected_no_internet_4_bar" title="signal_cellular_connected_no_internet_4_bar" />
<AbritesIcon icon="signal_cellular_no_sim" title="signal_cellular_no_sim" />
<AbritesIcon icon="signal_cellular_null" title="signal_cellular_null" />
<AbritesIcon icon="signal_cellular_off" title="signal_cellular_off" />
<AbritesIcon icon="signal_wifi_4_bar" title="signal_wifi_4_bar" />
<AbritesIcon icon="signal_wifi_4_bar_lock" title="signal_wifi_4_bar_lock" />
<AbritesIcon icon="signal_wifi_off" title="signal_wifi_off" />
<AbritesIcon icon="sim_card" title="sim_card" />
<AbritesIcon icon="sim_card_alert" title="sim_card_alert" />
<AbritesIcon icon="skip_next" title="skip_next" />
<AbritesIcon icon="skip_previous" title="skip_previous" />
<AbritesIcon icon="slideshow" title="slideshow" />
<AbritesIcon icon="slow_motion_video" title="slow_motion_video" />
<AbritesIcon icon="smartphone" title="smartphone" />
<AbritesIcon icon="smoke_free" title="smoke_free" />
<AbritesIcon icon="smoking_rooms" title="smoking_rooms" />
<AbritesIcon icon="sms" title="sms" />
<AbritesIcon icon="sms_failed" title="sms_failed" />
<AbritesIcon icon="snooze" title="snooze" />
<AbritesIcon icon="sort" title="sort" />
<AbritesIcon icon="sort_by_alpha" title="sort_by_alpha" />
<AbritesIcon icon="spa" title="spa" />
<AbritesIcon icon="space_bar" title="space_bar" />
<AbritesIcon icon="speaker" title="speaker" />
<AbritesIcon icon="speaker_group" title="speaker_group" />
<AbritesIcon icon="speaker_notes" title="speaker_notes" />
<AbritesIcon icon="speaker_notes_off" title="speaker_notes_off" />
<AbritesIcon icon="speaker_phone" title="speaker_phone" />
<AbritesIcon icon="spellcheck" title="spellcheck" />
<AbritesIcon icon="star" title="star" />
<AbritesIcon icon="star_border" title="star_border" />
<AbritesIcon icon="star_half" title="star_half" />
<AbritesIcon icon="stars" title="stars" />
<AbritesIcon icon="stay_current_landscape" title="stay_current_landscape" />
<AbritesIcon icon="stay_current_portrait" title="stay_current_portrait" />
<AbritesIcon icon="stay_primary_landscape" title="stay_primary_landscape" />
<AbritesIcon icon="stay_primary_portrait" title="stay_primary_portrait" />
<AbritesIcon icon="stop" title="stop" />
<AbritesIcon icon="stop_screen_share" title="stop_screen_share" />
<AbritesIcon icon="storage" title="storage" />
<AbritesIcon icon="store" title="store" />
<AbritesIcon icon="store_mall_directory" title="store_mall_directory" />
<AbritesIcon icon="straighten" title="straighten" />
<AbritesIcon icon="streetview" title="streetview" />
<AbritesIcon icon="strikethrough_s" title="strikethrough_s" />
<AbritesIcon icon="style" title="style" />
<AbritesIcon icon="subdirectory_arrow_left" title="subdirectory_arrow_left" />
<AbritesIcon icon="subdirectory_arrow_right" title="subdirectory_arrow_right" />
<AbritesIcon icon="subject" title="subject" />
<AbritesIcon icon="subscriptions" title="subscriptions" />
<AbritesIcon icon="subtitles" title="subtitles" />
<AbritesIcon icon="subway" title="subway" />
<AbritesIcon icon="supervisor_account" title="supervisor_account" />
<AbritesIcon icon="surround_sound" title="surround_sound" />
<AbritesIcon icon="swap_calls" title="swap_calls" />
<AbritesIcon icon="swap_horiz" title="swap_horiz" />
<AbritesIcon icon="swap_vert" title="swap_vert" />
<AbritesIcon icon="swap_vertical_circle" title="swap_vertical_circle" />
<AbritesIcon icon="switch_camera" title="switch_camera" />
<AbritesIcon icon="switch_video" title="switch_video" />
<AbritesIcon icon="sync" title="sync" />
<AbritesIcon icon="sync_disabled" title="sync_disabled" />
<AbritesIcon icon="sync_problem" title="sync_problem" />
<AbritesIcon icon="system_update" title="system_update" />
<AbritesIcon icon="system_update_alt" title="system_update_alt" />
<AbritesIcon icon="tab" title="tab" />
<AbritesIcon icon="tab_unselected" title="tab_unselected" />
<AbritesIcon icon="tablet" title="tablet" />
<AbritesIcon icon="tablet_android" title="tablet_android" />
<AbritesIcon icon="tablet_mac" title="tablet_mac" />
<AbritesIcon icon="tag_faces" title="tag_faces" />
<AbritesIcon icon="tap_and_play" title="tap_and_play" />
<AbritesIcon icon="terrain" title="terrain" />
<AbritesIcon icon="text_fields" title="text_fields" />
<AbritesIcon icon="text_format" title="text_format" />
<AbritesIcon icon="textsms" title="textsms" />
<AbritesIcon icon="texture" title="texture" />
<AbritesIcon icon="theaters" title="theaters" />
<AbritesIcon icon="thumb_down" title="thumb_down" />
<AbritesIcon icon="thumb_up" title="thumb_up" />
<AbritesIcon icon="thumbs_up_down" title="thumbs_up_down" />
<AbritesIcon icon="time_to_leave" title="time_to_leave" />
<AbritesIcon icon="timelapse" title="timelapse" />
<AbritesIcon icon="timeline" title="timeline" />
<AbritesIcon icon="timer" title="timer" />
<AbritesIcon icon="timer_10" title="timer_10" />
<AbritesIcon icon="timer_3" title="timer_3" />
<AbritesIcon icon="timer_off" title="timer_off" />
<AbritesIcon icon="title" title="title" />
<AbritesIcon icon="toc" title="toc" />
<AbritesIcon icon="today" title="today" />
<AbritesIcon icon="toll" title="toll" />
<AbritesIcon icon="tonality" title="tonality" />
<AbritesIcon icon="touch_app" title="touch_app" />
<AbritesIcon icon="toys" title="toys" />
<AbritesIcon icon="track_changes" title="track_changes" />
<AbritesIcon icon="traffic" title="traffic" />
<AbritesIcon icon="train" title="train" />
<AbritesIcon icon="tram" title="tram" />
<AbritesIcon icon="transfer_within_a_station" title="transfer_within_a_station" />
<AbritesIcon icon="transform" title="transform" />
<AbritesIcon icon="translate" title="translate" />
<AbritesIcon icon="trending_down" title="trending_down" />
<AbritesIcon icon="trending_flat" title="trending_flat" />
<AbritesIcon icon="trending_up" title="trending_up" />
<AbritesIcon icon="tune" title="tune" />
<AbritesIcon icon="turned_in" title="turned_in" />
<AbritesIcon icon="turned_in_not" title="turned_in_not" />
<AbritesIcon icon="tv" title="tv" />
<AbritesIcon icon="unarchive" title="unarchive" />
<AbritesIcon icon="undo" title="undo" />
<AbritesIcon icon="unfold_less" title="unfold_less" />
<AbritesIcon icon="unfold_more" title="unfold_more" />
<AbritesIcon icon="update" title="update" />
<AbritesIcon icon="usb" title="usb" />
<AbritesIcon icon="verified_user" title="verified_user" />
<AbritesIcon icon="vertical_align_bottom" title="vertical_align_bottom" />
<AbritesIcon icon="vertical_align_center" title="vertical_align_center" />
<AbritesIcon icon="vertical_align_top" title="vertical_align_top" />
<AbritesIcon icon="vibration" title="vibration" />
<AbritesIcon icon="video_call" title="video_call" />
<AbritesIcon icon="video_label" title="video_label" />
<AbritesIcon icon="video_library" title="video_library" />
<AbritesIcon icon="videocam" title="videocam" />
<AbritesIcon icon="videocam_off" title="videocam_off" />
<AbritesIcon icon="videogame_asset" title="videogame_asset" />
<AbritesIcon icon="view_agenda" title="view_agenda" />
<AbritesIcon icon="view_array" title="view_array" />
<AbritesIcon icon="view_carousel" title="view_carousel" />
<AbritesIcon icon="view_column" title="view_column" />
<AbritesIcon icon="view_comfy" title="view_comfy" />
<AbritesIcon icon="view_compact" title="view_compact" />
<AbritesIcon icon="view_day" title="view_day" />
<AbritesIcon icon="view_headline" title="view_headline" />
<AbritesIcon icon="view_list" title="view_list" />
<AbritesIcon icon="view_module" title="view_module" />
<AbritesIcon icon="view_quilt" title="view_quilt" />
<AbritesIcon icon="view_stream" title="view_stream" />
<AbritesIcon icon="view_week" title="view_week" />
<AbritesIcon icon="vignette" title="vignette" />
<AbritesIcon icon="visibility" title="visibility" />
<AbritesIcon icon="visibility_off" title="visibility_off" />
<AbritesIcon icon="voice_chat" title="voice_chat" />
<AbritesIcon icon="voicemail" title="voicemail" />
<AbritesIcon icon="volume_down" title="volume_down" />
<AbritesIcon icon="volume_mute" title="volume_mute" />
<AbritesIcon icon="volume_off" title="volume_off" />
<AbritesIcon icon="volume_up" title="volume_up" />
<AbritesIcon icon="vpn_key" title="vpn_key" />
<AbritesIcon icon="vpn_lock" title="vpn_lock" />
<AbritesIcon icon="wallpaper" title="wallpaper" />
<AbritesIcon icon="warning" title="warning" />
<AbritesIcon icon="watch" title="watch" />
<AbritesIcon icon="watch_later" title="watch_later" />
<AbritesIcon icon="wb_auto" title="wb_auto" />
<AbritesIcon icon="wb_cloudy" title="wb_cloudy" />
<AbritesIcon icon="wb_incandescent" title="wb_incandescent" />
<AbritesIcon icon="wb_iridescent" title="wb_iridescent" />
<AbritesIcon icon="wb_sunny" title="wb_sunny" />
<AbritesIcon icon="wc" title="wc" />
<AbritesIcon icon="web" title="web" />
<AbritesIcon icon="web_asset" title="web_asset" />
<AbritesIcon icon="weekend" title="weekend" />
<AbritesIcon icon="whatshot" title="whatshot" />
<AbritesIcon icon="widgets" title="widgets" />
<AbritesIcon icon="wifi" title="wifi" />
<AbritesIcon icon="wifi_lock" title="wifi_lock" />
<AbritesIcon icon="wifi_tethering" title="wifi_tethering" />
<AbritesIcon icon="work" title="work" />
<AbritesIcon icon="wrap_text" title="wrap_text" />
<AbritesIcon icon="youtube_searched_for" title="youtube_searched_for" />
<AbritesIcon icon="zoom_in" title="zoom_in" />
<AbritesIcon icon="zoom_out" title="zoom_out" />
<AbritesIcon icon="zoom_out_map" title="zoom_out_map" />
`;
</script>

<template>
  <h2 class="component-title" id="selector">
    <a
      :href="`${Config.componentsUrl}/components/icon/Icon.vue`"
      target="_blank"
      rel="noopener"
      >AbritesIcon</a
    >
    <span>&lt;AbritesIcon&gt;&lt;/AbritesIcon&gt;</span>
  </h2>

  <h3 class="section-title" id="inputs">Inputs</h3>
  <ul>
    <li>
      <strong>icon</strong> <code>string</code>
      <p>
        The icon name/ligature to display. Full list with all icons and ther
        names could be found at
        <a
          :href="`https://shanfan.github.io/material-icons-cheatsheet/`"
          target="_blank"
          rel="noopener"
          >https://shanfan.github.io/material-icons-cheatsheet/</a
        >.
      </p>
    </li>
  </ul>

  <h3 class="section-title" id="styling">Styling</h3>
  <p>
    The following attributes and/or classes could be used to customize the
    component style:
  </p>
  <ul>
    <li><code>[accent]</code>, <code>.accent</code></li>
    <li><code>[danger]</code>, <code>.danger</code></li>
    <li><code>[success]</code>, <code>.success</code></li>
    <li><code>[warning]</code>, <code>.warning</code></li>
    <li><code>[light]</code>, <code>.light</code></li>
    <li><code>[dark]</code>, <code>.dark</code></li>
    <li><code>[faded]</code>, <code>.faded</code></li>
    <li><code>[small]</code>, <code>.small</code></li>
    <li><code>[large]</code>, <code>.large</code></li>
    <li><code>[rotate-90]</code>, <code>.rotate-90</code></li>
    <li><code>[rotate-180]</code>, <code>.rotate-180</code></li>
    <li><code>[rotate-270]</code>, <code>.rotate-270</code></li>
  </ul>

  <h3 class="section-title" id="examples">Examples</h3>
  <Preview title="Colors" :htmlExample="htmlColorsExample" />

  <Preview title="Faded" :htmlExample="htmlFadedExample" />

  <Preview title="Sizes" :htmlExample="htmlSizesExample" />

  <Preview title="Rotates" :htmlExample="htmlRotatesExample" />

  <Preview title="All icons" :htmlExample="htmlListExample" />
</template>

<style></style>
